<?php

namespace Database\Seeders;

use App\Models\Umkm;
use Illuminate\Database\Seeder;

class UmkmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $umkmData = [
            [
                'name' => 'Kerupuk Bola Tahu Sawotratap',
                'category' => 'Kuliner',
                'price' => 15000,
                'image' => 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&h=600&fit=crop',
                'description' => 'Kerupuk bola tahu renyah khas Sawotratap dengan cita rasa yang nikmat dan gurih. Dibuat dari bahan pilihan dan diolah dengan resep turun temurun. Cocok untuk camilan keluarga atau oleh-oleh khas desa.',
                'seller' => 'Ibu Siti',
                'location' => 'RT 03 RW 05',
                'stock' => 45,
                'phone' => '6281234567890',
                'status' => 'active',
            ],
            [
                'name' => 'Batang Cabai Isi Teri',
                'category' => 'Kuliner',
                'price' => 25000,
                'image' => 'https://images.unsplash.com/photo-1600886455078-e9b73c58f09f?w=800&h=600&fit=crop',
                'description' => 'Camilan pedas dan gurih dengan isian teri pilihan, sempurna untuk dihidangkan. Tingkat kepedasan bisa disesuaikan dengan permintaan. Produk hygenis dan tahan lama.',
                'seller' => 'Bapak Ahmad',
                'location' => 'RT 02 RW 04',
                'stock' => 32,
                'phone' => '6281234567891',
                'status' => 'active',
            ],
            [
                'name' => 'Batik Tulis Khas Desa',
                'category' => 'Kerajinan',
                'price' => 150000,
                'image' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&h=600&fit=crop',
                'description' => 'Batik tulis dengan motif tradisional yang indah, dibuat oleh pengrajin lokal. Setiap lembar batik adalah karya seni yang unik. Material kain berkualitas premium dan pewarna ramah lingkungan.',
                'seller' => 'Ibu Ratih',
                'location' => 'RT 01 RW 03',
                'stock' => 12,
                'phone' => '6281234567892',
                'status' => 'active',
            ],
            [
                'name' => 'Anyaman Bambu',
                'category' => 'Kerajinan',
                'price' => 35000,
                'image' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=600&fit=crop',
                'description' => 'Kerajinan anyaman tangan dari bambu berkualitas, cocok untuk dekorasi rumah. Produk ramah lingkungan dan tahan lama. Dapat digunakan sebagai tempat penyimpanan atau hiasan dinding.',
                'seller' => 'Bapak Hendra',
                'location' => 'RT 04 RW 05',
                'stock' => 28,
                'phone' => '6281234567893',
                'status' => 'active',
            ],
            [
                'name' => 'Tape Singkong Premium',
                'category' => 'Kuliner',
                'price' => 20000,
                'image' => 'https://images.unsplash.com/photo-1590080876-6022d3a23896?w=800&h=600&fit=crop',
                'description' => 'Tape singkong yang difermentasi dengan baik, manis dan lezat alami. Tanpa bahan pengawet, diproduksi fresh setiap hari. Tingkat kematangan sempurna untuk rasa optimal.',
                'seller' => 'Ibu Marni',
                'location' => 'RT 05 RW 02',
                'stock' => 50,
                'phone' => '6281234567894',
                'status' => 'active',
            ],
            [
                'name' => 'Tempe Goreng Crispy',
                'category' => 'Kuliner',
                'price' => 12000,
                'image' => 'https://images.unsplash.com/photo-1599599810694-b5ac4dd577b7?w=800&h=600&fit=crop',
                'description' => 'Tempe goreng dengan tepung khusus yang membuat tekstur super renyah. Digoreng dengan minyak bersih dan higienis. Tahan lama tanpa melempem.',
                'seller' => 'Ibu Dewi',
                'location' => 'RT 03 RW 04',
                'stock' => 60,
                'phone' => '6281234567895',
                'status' => 'active',
            ],
            [
                'name' => 'Tas Rajut Handmade',
                'category' => 'Kerajinan',
                'price' => 85000,
                'image' => 'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=800&h=600&fit=crop',
                'description' => 'Tas anyaman tangan dengan desain unik dan berwarna cerah, tahan lama. Cocok untuk daily use atau acara formal. Tersedia berbagai warna dan ukuran.',
                'seller' => 'Ibu Eni',
                'location' => 'RT 02 RW 02',
                'stock' => 18,
                'phone' => '6281234567896',
                'status' => 'active',
            ],
            [
                'name' => 'Dodol Nangka Sawotratap',
                'category' => 'Kuliner',
                'price' => 30000,
                'image' => 'https://images.unsplash.com/photo-1599599810964-92ff8742f3f3?w=800&h=600&fit=crop',
                'description' => 'Dodol dengan isi nangka segar, lembut dan nikmat di lidah. Manis alami dari buah nangka pilihan. Dikemas higienis dan tahan hingga 2 minggu.',
                'seller' => 'Bapak Sugiono',
                'location' => 'RT 01 RW 05',
                'stock' => 25,
                'phone' => '6281234567897',
                'status' => 'active',
            ],
            [
                'name' => 'Keramik Gerabah',
                'category' => 'Kerajinan',
                'price' => 40000,
                'image' => 'https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=800&h=600&fit=crop',
                'description' => 'Gerabah buatan tangan dengan desain artistik, cocok untuk koleksi. Dibuat dengan teknik tradisional dan dibakar dengan sempurna. Dapat custom desain sesuai permintaan.',
                'seller' => 'Bapak Toto',
                'location' => 'RT 04 RW 03',
                'stock' => 15,
                'phone' => '6281234567898',
                'status' => 'active',
            ],
            [
                'name' => 'Minyak Kelapa Murni',
                'category' => 'Kuliner',
                'price' => 45000,
                'image' => 'https://images.unsplash.com/photo-1599022051969-91e6c3b35797?w=800&h=600&fit=crop',
                'description' => 'Minyak kelapa murni tanpa pengawet, menggunakan proses tradisional. 100% dari buah kelapa segar pilihan. Kaya akan manfaat kesehatan dan aroma harum alami.',
                'seller' => 'Ibu Rohani',
                'location' => 'RT 03 RW 01',
                'stock' => 35,
                'phone' => '6281234567899',
                'status' => 'active',
            ],
            [
                'name' => 'Boneka Kain Tradisional',
                'category' => 'Kerajinan',
                'price' => 50000,
                'image' => 'https://images.unsplash.com/photo-1595777712802-46a16b984e58?w=800&h=600&fit=crop',
                'description' => 'Boneka buatan tangan dengan kain batik lokal, unik dan bercerita. Aman untuk anak-anak dan menjadi koleksi menarik. Setiap boneka dibuat dengan penuh cinta.',
                'seller' => 'Ibu Tri',
                'location' => 'RT 02 RW 03',
                'stock' => 22,
                'phone' => '6281234567900',
                'status' => 'active',
            ],
            [
                'name' => 'Kacang Goreng Pedas',
                'category' => 'Kuliner',
                'price' => 18000,
                'image' => 'https://images.unsplash.com/photo-1585707002059-3b73199cff31?w=800&h=600&fit=crop',
                'description' => 'Kacang goreng dengan bumbu pedas khas yang membuat ketagihan. Renyah maksimal dan tingkat kepedasan pas. Cocok untuk teman nonton atau bersantai.',
                'seller' => 'Ibu Sunik',
                'location' => 'RT 05 RW 04',
                'stock' => 55,
                'phone' => '6281234567901',
                'status' => 'active',
            ],
            [
                'name' => 'Emping Melinjo Gurih',
                'category' => 'Kuliner',
                'price' => 22000,
                'image' => 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&h=600&fit=crop',
                'description' => 'Emping melinjo asli buatan sendiri dengan rasa gurih alami. Tipis dan renyah, perfect untuk pelengkap soto atau dimakan langsung.',
                'seller' => 'Ibu Wati',
                'location' => 'RT 01 RW 02',
                'stock' => 40,
                'phone' => '6281234567902',
                'status' => 'active',
            ],
            [
                'name' => 'Gantungan Kunci Kayu',
                'category' => 'Kerajinan',
                'price' => 15000,
                'image' => 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&h=600&fit=crop',
                'description' => 'Gantungan kunci dari kayu jati dengan ukiran nama custom. Cocok untuk souvenir atau hadiah. Finishing halus dan tahan lama.',
                'seller' => 'Bapak Rudi',
                'location' => 'RT 02 RW 05',
                'stock' => 65,
                'phone' => '6281234567903',
                'status' => 'active',
            ],
            [
                'name' => 'Sambal Pecel Homemade',
                'category' => 'Kuliner',
                'price' => 18000,
                'image' => 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&h=600&fit=crop',
                'description' => 'Sambal pecel dengan resep rahasia yang pedas dan gurih. Tanpa pengawet, cocok untuk pecel sayur atau pelengkap nasi goreng.',
                'seller' => 'Ibu Laras',
                'location' => 'RT 04 RW 02',
                'stock' => 30,
                'phone' => '6281234567904',
                'status' => 'active',
            ],
        ];

        foreach ($umkmData as $data) {
            Umkm::create($data);
        }
    }
}
